grafana_image: "grafana/grafana:{{ grafana_image_tag }}"
grafana_image_tag: "13.1.1-slim"
grafana_root_url: "https://{{ domain }}/"
grafana_csrf_trusted_origin: "https://{{ domain }}"

grafana_config_root: "/etc/grafana"
grafana_provisioning_path: "{{ grafana_config_root }}/provisioning"
grafana_datasources_path: "{{ grafana_provisioning_path }}/datasources"
grafana_dashboard_providers_path: "{{ grafana_provisioning_path }}/dashboards"
grafana_dashboards_path: "{{ grafana_config_root }}/dashboards"
