db_host: "db-postgresql-hexlet4-do-user-13876020-0.i.db.ondigitalocean.com"
db_port: "25060"
db_name: "defaultdb"
db_sslmode: "require"

domain_name: "bulletins.artem.diy"

ports:
  - "23332" # custom SSH port
  - "80"
  - "443"
