- name: Create grafana provisioning directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ grafana_datasources_path }}"
    - "{{ grafana_dashboard_providers_path }}"
    - "{{ grafana_dashboards_path }}"

- name: Copy datasource provisioning
  ansible.builtin.template:
    src: "datasources/{{ item }}.j2"
    dest: "{{ grafana_datasources_path }}/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop:
    - prometheus.yml
    - loki.yml
  notify: Restart grafana

- name: Copy dashboard providers provisioning
  ansible.builtin.template:
    src: dashboard_providers/default.yml.j2
    dest: "{{ grafana_dashboard_providers_path }}/default.yml"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: Restart grafana

- name: Copy provisioning
  ansible.builtin.copy:
    src: dashboards/
    dest: "{{ grafana_dashboards_path }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: Restart grafana

- name: Create Grafana data volume
  community.docker.docker_volume:
    name: grafana-data

- name: Create Grafana container
  community.docker.docker_container:
    name: grafana
    state: started
    image: "{{ grafana_image }}"
    volumes:
      - "{{ grafana_provisioning_path }}:{{ grafana_provisioning_path }}:ro"
      - "{{ grafana_dashboards_path }}:{{ grafana_dashboards_path }}:ro"
      - "grafana-data:/var/lib/grafana"
    networks:
      - name: "{{ monitoring_network }}"
    ports:
      - "127.0.0.1:3000:3000"
    env:
      GF_SECURITY_ADMIN_USER: "{{ grafana_admin_user }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
      GF_SERVER_ROOT_URL: "{{ grafana_root_url }}"
      GF_SECURITY_CSRF_TRUSTED_ORIGINS: "{{ grafana_csrf_trusted_origin }}"

    restart_policy: unless-stopped
  no_log: "{{ no_log | default(true) }}"

- name: Allow docker network to reach prometheus port
  community.general.ufw:
    rule: allow
    port: "{{ prometheus_port }}"
    proto: tcp
    from_ip: "172.16.0.0/12"
