loki_release_version: "3.7.6"
loki_image: "grafana/loki:{{ loki_release_version }}"
loki_config_directory: "/etc/loki"
loki_config_path: "{{ loki_config_directory }}/loki.yml"

loki_data_mnt: "/loki"
