all:
  children:
    molecule:
      hosts:
        nginx-exporter-ubuntu2404:
          ansible_connection: community.docker.docker
          container_image: geerlingguy/docker-ubuntu2404-ansible:latest
