all:
  children:
    molecule:
      hosts:
        nginx-exporter-ubuntu2404:
          ansible_connection: community.docker.docker
          container_image: geerlingguy/docker-ubuntu2404-ansible@sha256:bab98bf6bf4b65908a5cf46a08a9a20c95916c500e83894b5f63a82f1305a778
