- name: Create container instances
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create containers from inventory
      community.docker.docker_container:
        name: "{{ item }}"
        hostname: "{{ item }}"
        image: "{{ hostvars[item].container_image }}"
        privileged: true
        cgroupns_mode: host
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:rw
        state: started
      loop: "{{ groups['molecule'] }}"

    - name: Wait for systemd inside the containers
      ansible.builtin.command: systemctl is-system-running --wait  # noqa: command-instead-of-module
      register: nginx_exporter_test_systemd_state
      failed_when: nginx_exporter_test_systemd_state.stdout not in ['running', 'degraded']
      changed_when: false
      delegate_to: "{{ item }}"
      loop: "{{ groups['molecule'] }}"
