- name: Destroy container instances
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Remove containers from inventory
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
      loop: "{{ groups['molecule'] }}"
