- name: Create ssl_certificate directory
  ansible.builtin.file:
    path: "{{ certbot_webroot }}"
    state: directory
    mode: "0755"

- name: Initial Certbot Run
  ansible.builtin.include_role:
    name: geerlingguy.certbot

- name: Re-check nginx configuration
  ansible.builtin.include_role:
    name: prepare_nginx

- name: Re-Run nginx with TLS
  ansible.builtin.include_role:
    name: geerlingguy.nginx

- name: Run handlers after TLS certificate issuance
  ansible.builtin.meta: flush_handlers

- name: Set renew cert hook
  ansible.builtin.copy:
    src: deploy_auto_renew.sh
    dest: /etc/letsencrypt/renewal-hooks/deploy/
    owner: "root"
    mode: "0755"

- name: Turn off certbot.timer
  ansible.builtin.systemd_service:
    name: certbot.timer
    enabled: false
    state: stopped
