[droplets]
167.99.132.241
[droplets:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user=devops
ansible_port=23332
ansible_host=167.99.132.241

non_root_user_name=devops
password_auth_enabled=no
ssh_port=23332
root_login_enabled=no
ansible_ssh_private_key_file=~/.ssh/devops

