[droplets:children]
application
prometheus

[application]
167.99.132.241

[prometheus]
206.189.63.36

[droplets:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user={{ non_root_user_name }}
ansible_port={{ ssh_port }}
