[droplets:children]
application
monitoring

[application]
165.232.125.175

[monitoring]
165.227.174.50

[droplets:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user={{ non_root_user_name }}
ansible_port={{ ssh_port }}
