- name: Prometheus
  hosts: monitoring
  become: true

  pre_tasks:
    - name: Install docker
      ansible.builtin.include_role:
        name: geerlingguy.docker

    - name: Create a docker network
      community.docker.docker_network:
        name: "{{ monitoring_network }}"

  roles:
    - prometheus.prometheus.node_exporter
    - prometheus
