- name: Prometheus
  hosts: monitoring
  become: true

  pre_tasks:
    - name: Create prometheus config directory
      ansible.builtin.file:
        path: "{{ prometheus_config_directory }}"
        state: directory
        mode: "0755"

    - name: Copy Prometheus config
      ansible.builtin.template:
        src: prometheus/prometheus.yml.j2
        dest: "{{ prometheus_config_directory }}/prometheus.yml"
        owner: "root"
        mode: "0644"
        validate: >-
            docker run --rm --user root
            -v %s:/tmp/prometheus.yml:ro
            --entrypoint promtool prom/prometheus
            check config /tmp/prometheus.yml
      notify: Restart prometheus

  roles:
    - geerlingguy.docker
    - prometheus.prometheus.node_exporter

  tasks:
    - name: Create a network
      community.docker.docker_network:
        name: "{{ monitoring_network }}"

    - name: Create a Prometheus data volume
      community.docker.docker_volume:
        name: prometheus-data

    - name: Create Prometheus container
      community.docker.docker_container:
        name: prometheus
        state: started
        image: prom/prometheus
        volumes:
          - "{{ prometheus_config_directory }}:{{ prometheus_config_directory }}:ro"
          - "prometheus-data:/prometheus"
        networks:
          - name: "{{ monitoring_network }}"
        ports:
          - "127.0.0.1:9090:9090"
        restart_policy: always
    - name: Allow docker network to reach node_exporter
      community.general.ufw:
        rule: allow
        port: "{{ node_exporter_port }}"
        proto: tcp
        from_ip: "172.16.0.0/12"


  handlers:
    - name: Restart prometheus
      ansible.builtin.command: docker kill -s HUP prometheus
