galaxy_info:
  role_name: nginx_exporter
  namespace: artem_stepanenko
  author: Artem Stepanenko
  description: Build nginx exporter
  license: MIT

  min_ansible_version: "2.1"

  galaxy_tags: []

dependencies: []
