{
 "title": "Bulletins App",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Bulletins App",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application Uptime",
     "type": "state-timeline",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "up{job=\"application\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "JVM Heap stat (% of committed) ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(node) (jvm_memory_used_bytes{area=\"heap\"})/sum by(node) (jvm_memory_max_bytes{area=\"heap\" })",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "GC Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum[5m])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count[5m]))",
       "legendFormat": "RPS"
      }
     ]
    },
    {
     "title": "HTTP Status codes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum by(status) (rate(http_server_requests_seconds_count[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "5xx Errors Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": " (\n    (\n      sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[5m]))\n      or\n      sum(rate(http_server_requests_seconds_count[5m])) * 0\n    )\n    /\n    sum(rate(http_server_requests_seconds_count[5m]))\n  )\n",
       "legendFormat": "5xx Errors rate"
      }
     ]
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Up-times",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "nginx_up{job=\"nginx\"}",
     "legendFormat": "Nginx up-time"
    },
    {
     "expr": "up{job=\"nginx\"}",
     "legendFormat": "Exporter up-time"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[$__rate_interval])",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Nginx Connection Types",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "targets": [
    { "expr": "nginx_connections_waiting", "legendFormat": "Waiting" },
    { "expr": "nginx_connections_reading", "legendFormat": "Reading" },
    { "expr": "nginx_connections_writing", "legendFormat": "Writing" },
    { "expr": "nginx_connections_active", "legendFormat": "Active connections" }
   ]
  }
 ]
}