{
 "title": "System Usage",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(up{job=~\"node\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage (by mode)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(mode, node) (rate(node_cpu_seconds_total{job=~\"node\", mode!=\"idle\", node=~\"$node\"}[5m]))",
     "legendFormat": "{{node}} - {{mode}}"
    }
   ]
  },
  {
   "title": "Disk usage by size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum by (node) (node_filesystem_avail_bytes{node=~\"$node\",fstype=~\"ext4|vfat\"}) / sum by (node) (node_filesystem_size_bytes{node=~\"$node\",fstype=~\"ext4|vfat\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Usage (by node)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(node) (rate(node_cpu_seconds_total{job=~\"node\", mode!=\"idle\", node=~\"$node\"}[5m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk usage by filesystem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{node=~\"$node\",fstype=~\"ext4|vfat\"}) / (node_filesystem_size_bytes{node=~\"$node\",fstype=~\"ext4|vfat\"})",
     "legendFormat": "{{mountpoint}} {{node}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes{node=~\"$node\"} / node_memory_MemTotal_bytes{node=~\"$node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}